[project]
name = "ft-dao"
requirements = []
costs_version = 1

[contracts.ft-trait]
path = "contracts/ft-trait.clar"
depends_on = []

[contracts.ft-dao]
path = "contracts/ft-dao.clar"
depends_on = ["ft-trait"]
